"""Add Phase 2 Tables

Revision ID: eb6c29bae3a2
Revises: 
Create Date: 2026-02-05 12:59:50.165457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6c29bae3a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=True)
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('work_type', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('max_experience_years', sa.Integer(), nullable=True),
    sa.Column('employment_level', sa.String(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_pay_period', sa.String(), nullable=True),
    sa.Column('is_salary_visible', sa.Boolean(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('nice_to_have_skills', sa.JSON(), nullable=True),
    sa.Column('application_url', sa.String(), nullable=True),
    sa.Column('application_email', sa.String(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('roadmap_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('cgpa_10th', sa.Float(), nullable=True),
    sa.Column('cgpa_12th', sa.Float(), nullable=True),
    sa.Column('total_cgpa', sa.Float(), nullable=True),
    sa.Column('cgpa_sem1', sa.Float(), nullable=True),
    sa.Column('cgpa_sem2', sa.Float(), nullable=True),
    sa.Column('cgpa_sem3', sa.Float(), nullable=True),
    sa.Column('cgpa_sem4', sa.Float(), nullable=True),
    sa.Column('cgpa_sem5', sa.Float(), nullable=True),
    sa.Column('cgpa_sem6', sa.Float(), nullable=True),
    sa.Column('cgpa_sem7', sa.Float(), nullable=True),
    sa.Column('cgpa_sem8', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('career_interests', sa.JSON(), nullable=True),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('extracted_skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_career', sa.String(), nullable=True),
    sa.Column('roadmap_data', sa.JSON(), nullable=True),
    sa.Column('selected_variant', sa.Integer(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_table('job_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_interactions_id'), 'job_interactions', ['id'], unique=False)
    op.create_table('reward_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('reward_value', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['job_interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_logs_id'), 'reward_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_logs_id'), table_name='reward_logs')
    op.drop_table('reward_logs')
    op.drop_index(op.f('ix_job_interactions_id'), table_name='job_interactions')
    op.drop_table('job_interactions')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
